### ISSUE TITLE
--config param isn't accepted

### ISSUE THREAD

**Issue by kassim** [winify-ag/setup-phraseapp#12]
for some reason my workflow config as this
```
jobs:
  update-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: winify-ag/setup-phraseapp@v2.1.0
        with:
          version: 2.0.15
      - name: Pull translations
        run: phrase pull --access_token $PHRASE_ACCESS_TOKEN --config ./config/phraseapp-rider-config.yml
```
produces the error  `Error: no targets for download specified`
however when I change to 
```
jobs:
  update-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: winify-ag/setup-phraseapp@v2.1.0
        with:
          version: 2.0.15
      - name: Move Phrase config
        run: cp ./config/phraseapp-rider-config.yml .phrase.yml
      - name: Pull translations
        env:
          PHRASE_ACCESS_TOKEN: ${{ secrets.PHRASE_ACCESS_TOKEN }}
        run: phrase pull --access_token $PHRASE_ACCESS_TOKEN
```
it works

locally `phrase pull --access_token $PHRASE_ACCESS_TOKEN --config ./config/phraseapp-rider-config.yml` works
